name: Playwright QA Tests

on:
  push:
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.5'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Playwright Tests
        run: pytest
